### ISSUE TITLE
🐛 [BUG] 七夕版无限重启

### ISSUE THREAD

**Issue by wanwan411** [Team-Cemiuiler/Cemiuiler#296]
### 问题描述

从Cemiuiler_1.2.123_20230820_42efe5c8(123)_canary-signed到最新ci版无限重启，包括七夕版

### 模块日志

Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: Redmi K30 Pro
[Display]: SKQ1.211006.001 test-keys
[Android Version]: 12
[Android API Level]: 31
[System Locale]: zh_CN
[Process ID]: 3262
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20210731.0
[Version Code]: 202107310
[Error Type]: JVM
[Crash Time]: 2023-08-24T06:46:25.534
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
	at LSPHooker_.getStackTranslation(Unknown Source:14)
	at com.android.systemui.statusbar.notification.stack.StackScrollAlgorithm.updateClipping(StackScrollAlgorithm.java:192)
	at com.android.systemui.statusbar.notification.stack.MiuiStackScrollAlgorithm.updateClipping(MiuiStackScrollAlgorithm.kt:153)
	at com.android.systemui.statusbar.notification.stack.StackScrollAlgorithm.resetViewStates(StackScrollAlgorithm.java:118)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateChildren(NotificationStackScrollLayout.java:1134)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.access$100(NotificationStackScrollLayout.java:147)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout$1.onPreDraw(NotificationStackScrollLayout.java:320)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3476)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2277)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9037)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### 机型

Redmi K30 Pro

### MIUI 版本

MIUI14

### Android 版本

Android 12

### Cemiuiler 版本

1.2.123-20230822

**Comment by mu7220** [comment]
将于 1.2.124-20230824_beta 修复
