### ISSUE TITLE
🐛 [BUG] <系统框架-音量-默认调整音量 无法调整>

### ISSUE THREAD

**Issue by Ming-007** [Team-Cemiuiler/Cemiuiler#375]
### 问题描述

系统框架-音量-默认调整音量功能无法调整，一设置就闪退

### 模块日志

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:3012)
	at android.provider.Settings$Secure.putStringForUser(Settings.java:6249)
	at android.provider.Settings$Secure.putStringForUser(Settings.java:6234)
	at android.provider.Settings$Secure.putIntForUser(Settings.java:6449)
	at android.provider.Settings$Secure.putInt(Settings.java:6442)
	at r0.h.onPreferenceChange(Unknown Source:51)
	at moralnorm.preference.Preference.callChangeListener(Unknown Source:4)
	at moralnorm.preference.DropDownPreference$1$1.run(Unknown Source:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2331)
	at com.android.providers.settings.SettingsProvider.mutateSecureSetting(SettingsProvider.java:1768)
	at com.android.providers.settings.SettingsProvider.insertSecureSetting(SettingsProvider.java:1719)
	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:467)
	at android.content.ContentProvider.call(ContentProvider.java:2533)

### 复现步骤

```bash
系统框架-音量-默认调整音量功能无法调整，一设置就闪退
```

### 问题截图

![图片注释](图片链接)

### 机型

Redmi Note 12 Turbo

### MIUI 版本

MIUI14

### Android 版本

Android 13

### Cemiuiler 版本

1.2.125_20230912

**Comment by HChenX** [comment]
什么闪退？

**Comment by Fiz-Victor** [comment]
给root权限试试看？
